# Generated by Django 5.0.6 on 2024-05-26 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='RoadSings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.categorysigns')),
            ],
            options={
                'db_table': 'road_signs',
            },
        ),
    ]
