# Generated by Django 5.0.6 on 2024-05-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoadSings',
            new_name='RoadSigns',
        ),
    ]
